import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { getDefaultPortfolio, getPortfolioHoldings } from "@/lib/portfolio/queries";
import { calculatePortfolioValuation } from "@/lib/portfolio/valuation";
import { getLiveDashboardMarketData } from "@/lib/dashboard/live-market";
import { buildPortfolioIntelligence } from "@/lib/intelligence/calculations";
import AskAlphaForge from "@/components/intelligence/AskAlphaForge";
import ScenarioLab from "@/components/intelligence/ScenarioLab";
import Link from "next/link";

export default async function IntelligencePage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/sign-in");
  const portfolio = await getDefaultPortfolio(user.id);
  if (!portfolio) return <div className="space-y-6"><Header /><section className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-8 text-center"><h2 className="text-lg font-semibold text-white">Create a portfolio to unlock contextual intelligence</h2><p className="mx-auto mt-2 max-w-lg text-sm text-[#A1A7B3]">AlphaForge needs your own holdings before it can calculate concentration, movement, or scenarios.</p><Link href="/dashboard/portfolio" className="mt-5 inline-flex rounded-lg bg-[#2563EB] px-4 py-2 text-sm font-medium text-white">Create portfolio</Link></section></div>;
  const [holdings, liveMarket, paperAccount] = await Promise.all([getPortfolioHoldings(portfolio.id, user.id), getLiveDashboardMarketData(), supabase.from("paper_accounts").select("cash_balance").eq("user_id", user.id).maybeSingle()]);
  const valuation = await calculatePortfolioValuation(holdings, portfolio.cashBalance);
  const context = buildPortfolioIntelligence(valuation.valuedHoldings, portfolio.cashBalance, liveMarket);
  const options = liveMarket.filter((item) => item.price !== null && ["stock", "etf", "crypto"].includes(item.href.split("/")[3] ?? "")).map((item) => ({ symbol: item.symbol, name: item.name, price: item.price as number, assetType: item.symbol === "BTC" ? "crypto" as const : item.href.includes("/etf/") ? "etf" as const : "stock" as const, assetId: item.symbol === "BTC" ? "bitcoin" : item.symbol }));
  const largestLoser = [...context.holdings].filter((item) => item.unrealizedGain !== null).sort((a, b) => (a.unrealizedGain ?? 0) - (b.unrealizedGain ?? 0))[0];
  return <div className="space-y-6"><Header /><section className="rounded-xl border border-[#00C2A8]/20 bg-gradient-to-br from-[#00C2A8]/10 to-white/[0.02] p-5 sm:p-6"><p className="text-xs uppercase tracking-[0.18em] text-[#00C2A8]">Portfolio brief</p><h2 className="mt-2 text-2xl font-semibold text-white">Your portfolio is worth ${context.totalValue.toLocaleString(undefined, { maximumFractionDigits: 2 })}.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#CBD5E1]">{context.dailyChange === null ? "Current market movement is unavailable for enough holdings to reliably calculate today's portfolio move." : `Available market data indicates a ${context.dailyChange >= 0 ? "gain" : "loss"} of approximately $${Math.abs(context.dailyChange).toLocaleString(undefined, { maximumFractionDigits: 2 })} today.`} {context.largestPosition ? `${context.largestPosition.symbol} is your largest position at ${context.largestPosition.allocation.toFixed(1)}% of the portfolio.` : "Add priced holdings to receive position context."} {largestLoser ? `${largestLoser.symbol} has the lowest unrealized result.` : ""}</p></section><div className="grid gap-4 md:grid-cols-2"><HealthCard context={context} /><AskAlphaForge /></div><ScenarioLab context={context} options={options} paperBuyingPower={paperAccount.data?.cash_balance == null ? null : Number(paperAccount.data.cash_balance)} /><section className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-5"><h2 className="font-medium text-white">Position contribution</h2><p className="mt-1 text-xs text-[#A1A7B3]">Deterministic portfolio facts from available prices. No investment instruction is generated.</p><div className="mt-4 divide-y divide-white/[0.06]">{context.holdings.length ? context.holdings.slice(0, 8).map((holding) => <div key={holding.symbol} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><div><span className="font-medium text-white">{holding.symbol}</span><span className="ml-3 text-[#A1A7B3]">{holding.allocation.toFixed(1)}% allocation</span></div><div className="text-right"><span className={holding.dailyContribution === null || holding.dailyContribution >= 0 ? "text-[#00C2A8]" : "text-red-400"}>{holding.dailyContribution === null ? "Movement unavailable" : `${holding.dailyContribution >= 0 ? "+" : "-"}$${Math.abs(holding.dailyContribution).toLocaleString(undefined, { maximumFractionDigits: 2 })} today`}</span></div></div>) : <p className="py-6 text-sm text-[#A1A7B3]">No priced holdings are available for analysis.</p>}</div></section></div>;
}

function Header() { return <div><p className="text-xs uppercase tracking-wider text-[#00C2A8]">AlphaForge Intelligence</p><h1 className="mt-1 text-2xl font-semibold text-white">Your portfolio, explained</h1><p className="mt-1 text-sm text-[#A1A7B3]">Calculations come first. Explanations stay grounded in your portfolio and available market data.</p></div>; }
function HealthCard({ context }: { context: ReturnType<typeof buildPortfolioIntelligence> }) { return <section className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-5"><h2 className="font-medium text-white">Portfolio health</h2><div className="mt-4 grid grid-cols-2 gap-3"><Health label="Concentration" value={context.largestPosition && context.largestPosition.allocation >= 25 ? "High" : context.diversification} /><Health label="Largest position" value={context.largestPosition ? `${context.largestPosition.symbol} · ${context.largestPosition.allocation.toFixed(1)}%` : "Unavailable"} /><Health label="Top 3 positions" value={`${context.topThreeAllocation.toFixed(1)}%`} /><Health label="Cash" value={`${context.cashAllocation.toFixed(1)}%`} /><Health label="Crypto exposure" value={`${context.cryptoAllocation.toFixed(1)}%`} /><Health label="Equity exposure" value={`${context.equityAllocation.toFixed(1)}%`} /></div><p className="mt-4 text-sm leading-6 text-[#CBD5E1]">{context.risks[0]}</p></section>; }
function Health({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-[#0B0F1A] p-3"><p className="text-[10px] uppercase tracking-wider text-[#64748B]">{label}</p><p className="mt-1 truncate text-sm font-medium text-white">{value}</p></div>; }
