import assert from "node:assert/strict";
import test from "node:test";
import { calculateEquity, calculateUnrealizedPnl, executePaperTrade, type PaperAccountState } from "./accounting.ts";

const initial = (): PaperAccountState => ({ cash: 100000, positions: {}, realizedPnl: 0 });
test("handles single buy and buying power", () => { const result = executePaperTrade(initial(), "AAPL", "buy", 10, 100); assert.equal(result.account.cash, 99000); assert.deepEqual(result.account.positions.AAPL, { quantity: 10, averageCost: 100 }); });
test("calculates weighted average across buys", () => { const first = executePaperTrade(initial(), "AAPL", "buy", 10, 100).account; const result = executePaperTrade(first, "AAPL", "buy", 10, 120); assert.equal(result.account.cash, 97800); assert.deepEqual(result.account.positions.AAPL, { quantity: 20, averageCost: 110 }); });
test("calculates partial sell realized P/L and preserves basis", () => { let account = executePaperTrade(initial(), "AAPL", "buy", 10, 100).account; account = executePaperTrade(account, "AAPL", "buy", 10, 120).account; const result = executePaperTrade(account, "AAPL", "sell", 5, 130); assert.equal(result.execution.realizedPnl, 100); assert.equal(result.account.cash, 98450); assert.deepEqual(result.account.positions.AAPL, { quantity: 15, averageCost: 110 }); });
test("calculates full sell realized P/L and closes position", () => { const bought = executePaperTrade(initial(), "AAPL", "buy", 10, 100).account; const result = executePaperTrade(bought, "AAPL", "sell", 10, 130); assert.equal(result.account.realizedPnl, 300); assert.equal(result.execution.position, null); assert.equal(Object.keys(result.account.positions).length, 0); });
test("rejects insufficient cash, oversells, and invalid values", () => { assert.throws(() => executePaperTrade(initial(), "AAPL", "buy", 1001, 100)); const bought = executePaperTrade(initial(), "AAPL", "buy", 1, 100).account; assert.throws(() => executePaperTrade(bought, "AAPL", "sell", 2, 100)); assert.throws(() => executePaperTrade(bought, "AAPL", "sell", 0, 100)); assert.throws(() => executePaperTrade(bought, "AAPL", "sell", 1, Number.NaN)); });
test("calculates unrealized P/L and equity", () => { const account = executePaperTrade(initial(), "AAPL", "buy", 10, 100).account; assert.equal(calculateUnrealizedPnl(account.positions.AAPL, 130), 300); assert.equal(calculateEquity(account, { AAPL: 130 }), 100300); });
