import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getFeatureLimits, getUserPlan } from "@/lib/billing/entitlements";

const itemSchema = z.object({ assetType: z.enum(["stock", "etf", "crypto"]), assetId: z.string().trim().min(1).max(100), symbol: z.string().trim().min(1).max(20), name: z.string().trim().min(1).max(200) });
async function auth() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); return { supabase, user }; }
export async function GET() { const { supabase, user } = await auth(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { data, error } = await supabase.from("watchlist_items").select("id,asset_type,asset_id,symbol,name,created_at").eq("user_id", user.id).order("created_at", { ascending: false }); if (error) return NextResponse.json({ items: [] }); return NextResponse.json({ items: data ?? [] }); }
export async function POST(request: Request) { const { supabase, user } = await auth(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const parsed = itemSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid asset." }, { status: 400 }); const limit = getFeatureLimits(await getUserPlan()).watchlistLimit; const { count } = await supabase.from("watchlist_items").select("id", { count: "exact", head: true }).eq("user_id", user.id); if (limit !== null && (count ?? 0) >= limit) return NextResponse.json({ error: `Your watchlist limit is ${limit} assets on the Free plan. Upgrade to add more.` }, { status: 403 }); const { data, error } = await supabase.from("watchlist_items").insert({ user_id: user.id, asset_type: parsed.data.assetType, asset_id: parsed.data.assetId, symbol: parsed.data.symbol, name: parsed.data.name }).select("id,asset_type,asset_id,symbol,name,created_at").single(); if (error) return NextResponse.json({ error: error.code === "23505" ? "This asset is already on your watchlist." : "Watchlist could not be updated." }, { status: 400 }); return NextResponse.json({ item: data }); }
export async function DELETE(request: Request) { const { supabase, user } = await auth(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const id = new URL(request.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "Missing item." }, { status: 400 }); const { error } = await supabase.from("watchlist_items").delete().eq("id", id).eq("user_id", user.id); if (error) return NextResponse.json({ error: "Watchlist item could not be removed." }, { status: 400 }); return NextResponse.json({ success: true }); }
