import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getFeatureLimits, getUserPlan } from "@/lib/billing/entitlements";
const schema = z.object({ assetType: z.enum(["stock", "etf", "crypto"]), assetId: z.string().trim().min(1).max(100), symbol: z.string().trim().min(1).max(20), condition: z.enum(["above", "below"]), target: z.number().finite().positive() });
async function auth() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); return { supabase, user }; }
export async function GET() { const { supabase, user } = await auth(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { data } = await supabase.from("market_alerts").select("id,asset_type,asset_id,symbol,condition,target,status,triggered_at,trigger_price,created_at").eq("user_id", user.id).order("created_at", { ascending: false }); return NextResponse.json({ alerts: data ?? [] }); }
export async function POST(request: Request) { const { supabase, user } = await auth(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid alert." }, { status: 400 }); const limit = getFeatureLimits(await getUserPlan()).alertLimit; const { count } = await supabase.from("market_alerts").select("id", { count: "exact", head: true }).eq("user_id", user.id).eq("status", "active"); if (limit !== null && (count ?? 0) >= limit) return NextResponse.json({ error: `Your Free plan supports ${limit} active alerts. Upgrade to add more.` }, { status: 403 }); const { data, error } = await supabase.from("market_alerts").insert({ user_id: user.id, ...parsed.data }).select("id,asset_type,asset_id,symbol,condition,target,status,triggered_at,trigger_price,created_at").single(); if (error) return NextResponse.json({ error: "Alert could not be created." }, { status: 400 }); return NextResponse.json({ alert: data }); }
export async function DELETE(request: Request) { const { supabase, user } = await auth(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const id = new URL(request.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "Missing alert." }, { status: 400 }); const { error } = await supabase.from("market_alerts").delete().eq("id", id).eq("user_id", user.id); if (error) return NextResponse.json({ error: "Alert could not be deleted." }, { status: 400 }); return NextResponse.json({ success: true }); }
export async function PATCH(request: Request) { const { supabase, user } = await auth(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const body = await request.json().catch(() => null) as { id?: string; status?: string } | null; if (!body?.id || !["active", "disabled"].includes(body.status ?? "")) return NextResponse.json({ error: "Invalid alert update." }, { status: 400 }); const { error } = await supabase.from("market_alerts").update({ status: body.status }).eq("id", body.id).eq("user_id", user.id); if (error) return NextResponse.json({ error: "Alert could not be updated." }, { status: 400 }); return NextResponse.json({ success: true }); }
