import { createClient } from '@/lib/supabase/server';
import { redirect } from 'next/navigation';

export default async function PaperPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect('/sign-in');
  const { data: account } = await supabase.from('paper_accounts').select('cash_balance,starting_balance').eq('user_id', user.id).maybeSingle();
  const { data: positions } = await supabase.from('paper_positions').select('symbol,quantity,average_cost,realized_pnl').eq('user_id', user.id).order('symbol');
  const { data: orders } = await supabase.from('paper_orders').select('symbol,side,quantity,execution_price,gross_amount,status,created_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(20);
  return <div className="space-y-6"><div><p className="text-xs uppercase tracking-wider text-[#00C2A8]">Paper · Virtual · Simulated</p><h1 className="mt-1 text-2xl font-semibold text-white">Paper portfolio</h1><p className="mt-1 text-sm text-[#A1A7B3]">A separate $100,000 virtual account. No real money or securities are involved.</p></div><div className="grid gap-4 md:grid-cols-3"><Metric label="Virtual cash" value={Number(account?.cash_balance ?? 0)} /><Metric label="Starting balance" value={Number(account?.starting_balance ?? 100000)} /><Metric label="Positions" value={positions?.length ?? 0} numeric={false} /></div><section className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-5"><h2 className="font-medium text-white">Positions</h2>{positions?.length ? <div className="mt-4 divide-y divide-white/[0.06]">{positions.map((position) => <div key={position.symbol} className="flex items-center justify-between py-3 text-sm"><span className="text-white">{position.symbol}</span><span className="text-[#A1A7B3]">{Number(position.quantity).toLocaleString()} @ ${Number(position.average_cost).toFixed(2)}</span></div>)}</div> : <p className="mt-4 text-sm text-[#A1A7B3]">No paper positions yet. Use Paper Buy from an asset detail page when available.</p>}</section><section className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-5"><h2 className="font-medium text-white">Order history</h2>{orders?.length ? <div className="mt-4 divide-y divide-white/[0.06]">{orders.map((order, index) => <div key={`${order.symbol}-${order.created_at}-${index}`} className="flex items-center justify-between py-3 text-sm"><span className="text-white">{String(order.side).toUpperCase()} {order.quantity} {order.symbol}</span><span className="text-[#00C2A8]">{String(order.status).toUpperCase()}</span></div>)}</div> : <p className="mt-4 text-sm text-[#A1A7B3]">No paper orders yet.</p>}</section></div>;
}

function Metric({ label, value, numeric = true }: { label: string; value: number; numeric?: boolean }) { return <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-5"><p className="text-xs text-[#A1A7B3]">{label}</p><p className="mt-2 text-2xl font-semibold text-white">{numeric ? `$${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : value}</p></div>; }
