"use client";

import { useMemo, useState } from "react";
import { Brain, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { PortfolioIntelligence } from "@/lib/intelligence/calculations";

export default function AskAlphaForge({ context }: { context: PortfolioIntelligence }) {
  const prompts = ["Why did my portfolio move today?", "What is my biggest risk?", "Which position is hurting me most?", "How diversified is my portfolio?"];
  const [question, setQuestion] = useState("");
  const [submitted, setSubmitted] = useState<string | null>(null);
  const answer = useMemo(() => { if (!submitted) return null; const lower = submitted.toLowerCase(); if (lower.includes("today") || lower.includes("move")) return context.dailyChange === null ? "Current market movement data is unavailable for the holdings in this portfolio, so AlphaForge cannot reliably explain today's move." : `${context.dailyChange >= 0 ? "Your portfolio is up" : "Your portfolio is down"} approximately $${Math.abs(context.dailyChange).toLocaleString(undefined, { maximumFractionDigits: 2 })} today based on available market data. Coverage is ${context.dailyCoverage.toFixed(0)}% of priced positions.`; if (lower.includes("risk") || lower.includes("expos")) return context.risks[0]; if (lower.includes("hurting") || lower.includes("position")) { const loser = [...context.holdings].filter((item) => item.unrealizedGain !== null).sort((a, b) => (a.unrealizedGain ?? 0) - (b.unrealizedGain ?? 0))[0]; return loser ? `${loser.symbol} has the lowest unrealized result at $${(loser.unrealizedGain ?? 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}. This is a portfolio fact, not a recommendation.` : "Unrealized position data is unavailable."; } if (lower.includes("divers") || lower.includes("concentr")) return `Diversification is currently ${context.diversification.toLowerCase()}. Your largest three positions represent ${context.topThreeAllocation.toFixed(1)}% of the portfolio.`; return "Ask about today's movement, concentration, diversification, or a position. AlphaForge calculates the facts first and explains them without making a trade recommendation."; }, [submitted, context]);
  const submit = (value: string) => { const trimmed = value.trim(); if (trimmed) { setSubmitted(trimmed); setQuestion(trimmed); } };
  return <section className="rounded-xl border border-[#00C2A8]/20 bg-gradient-to-br from-[#00C2A8]/10 to-white/[0.02] p-5"><div className="flex items-center gap-2"><Brain className="h-5 w-5 text-[#00C2A8]" /><div><h2 className="font-medium text-white">Ask AlphaForge</h2><p className="text-xs text-[#A1A7B3]">Portfolio-aware analysis from your current data</p></div></div><div className="mt-4 flex flex-wrap gap-2">{prompts.map((prompt) => <button key={prompt} type="button" onClick={() => submit(prompt)} className="rounded-full border border-white/[0.08] px-3 py-2 text-left text-xs text-[#CBD5E1] hover:border-[#00C2A8]/40 hover:text-white">{prompt}</button>)}</div><form onSubmit={(event) => { event.preventDefault(); submit(question); }} className="mt-4 flex gap-2"><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about your portfolio..." className="min-w-0 flex-1 rounded-lg border border-white/[0.08] bg-[#0B0F1A] px-3 text-sm text-white outline-none focus:border-[#00C2A8]" /><Button type="submit" size="icon" aria-label="Ask AlphaForge"><Send className="h-4 w-4" /></Button></form>{submitted && answer && <div className="mt-4 rounded-lg border border-white/[0.06] bg-[#0B0F1A] p-4"><p className="text-xs uppercase tracking-wider text-[#00C2A8]">AlphaForge analysis</p><p className="mt-2 text-sm leading-6 text-[#CBD5E1]">{answer}</p><p className="mt-3 text-[11px] text-[#64748B]">Analysis is based on available portfolio and market data. It is not investment advice.</p></div>}</section>;
}
