"use client";

import { useMemo, useState } from "react";
import { Calculator, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { executePaperOrder } from "@/lib/paper/actions";
import type { PortfolioIntelligence } from "@/lib/intelligence/calculations";

interface Option { symbol: string; name: string; price: number; assetType: "stock" | "etf" | "crypto"; assetId: string; }
export default function ScenarioLab({ context, options, paperBuyingPower }: { context: PortfolioIntelligence; options: Option[]; paperBuyingPower: number | null }) {
  const [symbol, setSymbol] = useState(options[0]?.symbol ?? "");
  const [amount, setAmount] = useState("5000");
  const [mode, setMode] = useState<"simulate" | "paper">("simulate");
  const [message, setMessage] = useState<string | null>(null);
  const selected = options.find((option) => option.symbol === symbol);
  const result = useMemo(() => { if (!selected || !Number.isFinite(Number(amount)) || Number(amount) <= 0) return null; const purchase = Number(amount); const current = context.holdings.find((holding) => holding.symbol.toUpperCase() === selected.symbol.toUpperCase()); const before = current?.allocation ?? 0; const after = context.totalValue > 0 ? ((current?.value ?? 0) + purchase) / context.totalValue * 100 : 0; return { purchase, before, after, cashBefore: context.cashAllocation, cashAfter: context.totalValue > 0 ? Math.max(context.cashValue - purchase, 0) / context.totalValue * 100 : 0, buyingPowerAfter: paperBuyingPower === null ? null : paperBuyingPower - purchase, quantity: purchase / selected.price }; }, [amount, context, paperBuyingPower, selected]);
  const execute = async () => { if (!selected || !result || mode !== "paper" || result.buyingPowerAfter === null || result.buyingPowerAfter < 0) return; setMessage(null); const response = await executePaperOrder({ clientOrderId: crypto.randomUUID(), assetType: selected.assetType, assetId: selected.assetId, symbol: selected.symbol, side: "buy", quantity: result.quantity, executionPrice: selected.price }); setMessage(response.success ? "Paper order filled. Your paper account was updated." : response.error ?? "Paper order could not be executed."); };
  return <section className="rounded-xl border border-[#2563EB]/25 bg-[#2563EB]/5 p-5"><div className="flex items-center gap-2"><Calculator className="h-5 w-5 text-[#60A5FA]" /><div><h2 className="font-medium text-white">Scenario Lab</h2><p className="text-xs text-[#A1A7B3]">Explore the impact before you act. Simulation never changes your portfolio.</p></div></div>{options.length ? <><div className="mt-5 grid gap-3 sm:grid-cols-3"><label className="text-xs text-[#A1A7B3]">Asset<select value={symbol} onChange={(event) => setSymbol(event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-white/[0.08] bg-[#0B0F1A] px-3 text-sm text-white">{options.map((option) => <option key={option.symbol} value={option.symbol}>{option.symbol}</option>)}</select></label><label className="text-xs text-[#A1A7B3]">Buy amount<input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-white/[0.08] bg-[#0B0F1A] px-3 text-sm text-white" /></label><label className="text-xs text-[#A1A7B3]">Account context<select value={mode} onChange={(event) => setMode(event.target.value as "simulate" | "paper")} className="mt-1 h-10 w-full rounded-lg border border-white/[0.08] bg-[#0B0F1A] px-3 text-sm text-white"><option value="simulate">Simulation only</option><option value="paper">Paper account</option></select></label></div>{result && <div className="mt-5 grid gap-3 sm:grid-cols-2"><Comparison label={`${selected?.symbol} allocation`} before={`${result.before.toFixed(1)}%`} after={`${result.after.toFixed(1)}%`} /><Comparison label="Cash allocation" before={`${result.cashBefore.toFixed(1)}%`} after={`${result.cashAfter.toFixed(1)}%`} /><Comparison label="Buying power" before={paperBuyingPower === null ? "Unavailable" : `$${paperBuyingPower.toLocaleString()}`} after={result.buyingPowerAfter === null ? "Simulation only" : `$${result.buyingPowerAfter.toLocaleString()}`} /><div className="rounded-lg border border-white/[0.06] bg-[#0B0F1A] p-4"><p className="text-xs text-[#A1A7B3]">What changes</p><p className="mt-2 text-sm text-[#CBD5E1]">This purchase increases {selected?.symbol} exposure by {(result.after - result.before).toFixed(1)} percentage points. It does not change total portfolio value before market movement.</p></div></div>}{mode === "paper" && <Button type="button" onClick={execute} disabled={!result || result.buyingPowerAfter === null || result.buyingPowerAfter < 0} className="mt-5 w-full sm:w-auto">{message?.includes("filled") && <CheckCircle2 className="mr-2 h-4 w-4" />}Execute as Paper Trade</Button>}{message && <p className="mt-3 text-sm text-[#A1A7B3]">{message}</p>}</> : <p className="mt-5 text-sm text-[#A1A7B3]">Scenario prices are unavailable because no live provider quote is available.</p>}</section>;
}
function Comparison({ label, before, after }: { label: string; before: string; after: string }) { return <div className="rounded-lg border border-white/[0.06] bg-[#0B0F1A] p-4"><p className="text-xs text-[#A1A7B3]">{label}</p><div className="mt-2 flex items-end justify-between gap-2"><span className="text-lg font-medium text-white">{before}</span><span className="text-xs text-[#64748B]">→</span><span className="text-lg font-medium text-[#60A5FA]">{after}</span></div><div className="mt-1 flex justify-between text-[10px] uppercase tracking-wider text-[#64748B]"><span>Before</span><span>After</span></div></div>; }
