"use client";

import { useState } from "react";
import type { ReactNode } from "react";
import { Check, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";

const freeFeatures = ["Provider-backed market access", "Paper trading with $100,000 virtual capital", "1 portfolio", "20 watchlist assets", "5 active alerts", "Basic research"];
const proFeatures = ["Everything in Free", "Advanced AI research and history", "Portfolio Intelligence", "Scenario Lab", "Higher watchlist and alert limits", "Advanced analytics and exports"];

export default function PricingPlans() {
  const [interval, setInterval] = useState<"monthly" | "annual">("monthly");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  async function upgrade() { setLoading(true); setError(null); try { const response = await fetch("/api/billing/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ plan: "pro", interval }) }); const data = await response.json(); if (response.status === 401) { window.location.href = "/sign-in?next=/pricing"; return; } if (!response.ok || typeof data.authorizationUrl !== "string") throw new Error(data.error ?? "Checkout is currently unavailable."); window.location.href = data.authorizationUrl; } catch (caught) { setError(caught instanceof Error ? caught.message : "Checkout is currently unavailable."); setLoading(false); } }
  return <div className="mt-10"><div className="mx-auto flex w-fit rounded-lg border border-white/[0.08] bg-white/[0.02] p-1"><button type="button" onClick={() => setInterval("monthly")} className={`rounded-md px-4 py-2 text-sm ${interval === "monthly" ? "bg-[#2563EB] text-white" : "text-[#A1A7B3]"}`}>Monthly</button><button type="button" onClick={() => setInterval("annual")} className={`rounded-md px-4 py-2 text-sm ${interval === "annual" ? "bg-[#2563EB] text-white" : "text-[#A1A7B3]"}`}>Annual</button></div><div className="mt-6 grid gap-5 md:grid-cols-2"><Plan name="Free" price="$0" description="For exploring markets and learning with virtual capital." features={freeFeatures} /><Plan name="Pro" price={interval === "annual" ? "Annual Paystack plan" : "Monthly Paystack plan"} description="For deeper research and portfolio-aware intelligence." features={proFeatures} featured action={<Button type="button" onClick={upgrade} disabled={loading} className="mt-7 w-full bg-[#00C2A8] text-[#0B0F1A] hover:bg-[#00C2A8]/90">{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}{loading ? "Opening secure checkout..." : "Upgrade to Pro"}</Button>} /></div>{error && <p className="mt-4 text-center text-sm text-red-300">{error}</p>}<p className="mt-5 text-center text-xs text-[#64748B]">Payments are processed by Paystack. AlphaForge activates Pro only after server-side verification/webhook confirmation.</p></div>;
}

function Plan({ name, price, description, features, featured = false, action }: { name: string; price: string; description: string; features: string[]; featured?: boolean; action?: ReactNode }) { return <section className={`rounded-2xl border p-7 ${featured ? "border-[#2563EB] bg-[#2563EB]/10 shadow-xl shadow-[#2563EB]/10" : "border-white/[0.08] bg-white/[0.02]"}`}><div className="flex items-center justify-between"><h2 className="text-2xl font-medium">{name}</h2>{featured && <span className="rounded-full bg-[#2563EB]/20 px-2 py-1 text-xs uppercase tracking-wider text-[#60A5FA]">Recommended</span>}</div><p className="mt-5 text-xl text-white">{price}</p><p className="mt-2 min-h-12 text-sm text-[#A1A7B3]">{description}</p><ul className="mt-7 space-y-3 text-sm text-[#CBD5E1]">{features.map((feature) => <li key={feature} className="flex gap-2"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#00C2A8]" />{feature}</li>)}</ul>{action}</section>; }
