import Image from "next/image";
import { ExternalLink, Newspaper } from "lucide-react";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getCurrentNews, type NewsCategory } from "@/lib/market-data/news";

const categories: Array<{ value: NewsCategory; label: string }> = [
  { value: "latest", label: "Latest" },
  { value: "markets", label: "Markets" },
  { value: "stocks", label: "Stocks" },
  { value: "crypto", label: "Crypto" },
  { value: "macro", label: "Macro / Forex" },
];

function timeAgo(iso: string) {
  const diffMs = Date.now() - new Date(iso).getTime();
  const mins = Math.round(diffMs / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
}

export default async function NewsPage({ searchParams }: { searchParams: Promise<{ category?: string }> }) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/sign-in");

  const requested = (await searchParams).category;
  const category = categories.some((item) => item.value === requested) ? (requested as NewsCategory) : "latest";
  const news = await getCurrentNews(category);
  const [featured, ...rest] = news;

  return (
    <div className="space-y-6">
      <header>
        <div className="label-eyebrow">
          <span className="label-eyebrow-dot" />
          Sourced market news
        </div>
        <h1 className="text-page-title mt-1.5 text-white">News Intelligence</h1>
        <p className="mt-1 text-sm text-[#A1A7B3]">
          Current provider-sourced reporting, newest first. Headlines are never generated by AlphaForge.
        </p>
      </header>

      <nav className="flex flex-wrap gap-2" aria-label="News categories">
        {categories.map((item) => (
          <a
            key={item.value}
            href={`/dashboard/news?category=${item.value}`}
            className={`rounded-full border px-3 py-1.5 text-sm transition-colors ${
              item.value === category
                ? "border-[#00C2A8] bg-[#00C2A8]/10 text-[#00C2A8]"
                : "border-white/[0.08] text-[#A1A7B3] hover:text-white"
            }`}
          >
            {item.label}
          </a>
        ))}
      </nav>

      {news.length === 0 && (
        <section className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-10 text-center">
          <Newspaper className="mx-auto h-8 w-8 text-[#64748B]" />
          <h2 className="mt-3 font-medium text-white">News unavailable</h2>
          <p className="mt-1 text-sm text-[#A1A7B3]">The configured provider did not return current articles for this category.</p>
        </section>
      )}

      {featured && (
        <a
          href={featured.url}
          target="_blank"
          rel="noreferrer"
          className="group grid gap-0 overflow-hidden rounded-xl border border-white/[0.07] bg-white/[0.02] transition-colors hover:border-white/[0.12] md:grid-cols-[1.2fr_1fr]"
        >
          <div className="flex flex-col justify-center p-6">
            <span className="label-eyebrow">
              <span className="label-eyebrow-dot" />
              Top story
            </span>
            <h2 className="mt-3 text-xl font-semibold leading-snug text-white group-hover:text-[#00C2A8] sm:text-2xl">
              {featured.headline}
            </h2>
            <p className="mt-3 line-clamp-3 text-sm leading-relaxed text-[#A1A7B3]">
              {featured.summary || "Summary unavailable."}
            </p>
            <p className="num mt-4 text-xs text-[#5B6472]">
              {featured.source} · {timeAgo(featured.datetime)}
              {featured.relatedAsset ? ` · Affects ${featured.relatedAsset}` : ""}
            </p>
          </div>
          {featured.image ? (
            <div className="relative hidden min-h-[220px] md:block">
              <Image src={featured.image} alt="" fill className="object-cover" unoptimized />
              <div className="absolute inset-0 bg-gradient-to-l from-transparent to-[#0B0F1A]/40" />
            </div>
          ) : (
            <div className="hidden items-center justify-center border-l border-white/[0.06] bg-grid-fine md:flex">
              <Newspaper className="h-10 w-10 text-white/10" />
            </div>
          )}
        </a>
      )}

      {rest.length > 0 && (
        <div className="overflow-hidden rounded-xl border border-white/[0.06] bg-white/[0.02]">
          <div className="divide-y divide-white/[0.05]">
            {rest.map((item) => (
              <a
                key={item.id}
                href={item.url}
                target="_blank"
                rel="noreferrer"
                aria-label={`Open ${item.headline}`}
                className="group flex items-start justify-between gap-4 px-5 py-4 transition-colors hover:bg-white/[0.02]"
              >
                <div className="min-w-0">
                  <h3 className="text-sm font-medium leading-snug text-white group-hover:text-[#00C2A8]">
                    {item.headline}
                  </h3>
                  <p className="num mt-1.5 text-xs text-[#5B6472]">
                    {item.source} · {timeAgo(item.datetime)}
                    {item.relatedAsset ? ` · ${item.relatedAsset}` : ""}
                  </p>
                </div>
                <ExternalLink className="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-[#5B6472] group-hover:text-white" />
              </a>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
